# -*- coding: utf-8 -*-
"""Final Project VisDat Afkar&Diva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XbmB-ZkN7ZM9Kw_qz9KEiNqfsHn14vfa

#**Final Project Visualisasi Data - Kurs Mata Uang 5 Negara Terhadap US Dollar**

Nama Anggota :
1. Diva Annisa Febecca (1301204302)
2. Afkar Arthagesang Pradestoan (1301200131)

**Import Library**
"""

import pandas as pd
import numpy as np

# Bokeh Libraries
from datetime import date
from bokeh.io import curdoc
from bokeh.models import HoverTool
from bokeh.models.widgets import Tabs, Panel
from bokeh.layouts import column, row, layout
from bokeh.models.widgets import DateRangeSlider
from bokeh.io import output_file, output_notebook
from bokeh.models import ColumnDataSource, Legend
from bokeh.plotting import figure, show, reset_output

"""**Resource**"""

!wget 'https://drive.google.com/uc?export=download&id=1-McuXVysoT1TEu3L8nybtZw7TxjhACpa' -O kurs.csv

df = pd.read_csv("kurs.csv", parse_dates = ["Date"])
df.tail(5)

df_1 = pd.read_csv("kurs.csv", parse_dates = ["Date"], usecols=['Date', 'Indonesian Rupiah', 'U.S. Dollar'])
df_2 = pd.read_csv("kurs.csv", parse_dates = ["Date"], usecols=['Date', 'Thai Baht', 'U.S. Dollar'])
df_3 = pd.read_csv("kurs.csv", parse_dates = ["Date"], usecols=['Date', 'South African Rand', 'U.S. Dollar'])
df_4 = pd.read_csv("kurs.csv", parse_dates = ["Date"], usecols=['Date', 'Euro', 'U.S. Dollar'])
df_5 = pd.read_csv("kurs.csv", parse_dates = ["Date"], usecols=['Date', 'Japanese Yen', 'U.S. Dollar'])

df_1.rename(columns={'Indonesian Rupiah':'Rupiah'}, inplace=True)
df_2.rename(columns={'Thai Baht':'Baht'}, inplace=True)
df_3.rename(columns={'South African Rand':'Rand'}, inplace=True)
df_5.rename(columns={'Japanese Yen':'Yen'}, inplace=True)

df_1['Date'] = pd.to_datetime(df_1['Date'])
df_2['Date'] = pd.to_datetime(df_2['Date'])
df_3['Date'] = pd.to_datetime(df_3['Date'])
df_4['Date'] = pd.to_datetime(df_4['Date'])
df_5['Date'] = pd.to_datetime(df_5['Date'])

start_date = '01-01-2015'
end_date = '01-01-2018'

mask = (df_1['Date'] > start_date) & (df_1['Date'] <= end_date)

df1 = df_1.loc[mask]
df1.reset_index(drop=True, inplace=True)

df2 = df_2.loc[mask]
df2.reset_index(drop=True, inplace=True)

df3 = df_3.loc[mask]
df3.reset_index(drop=True, inplace=True)

df4 = df_4.loc[mask]
df4.reset_index(drop=True, inplace=True)

df5 = df_5.loc[mask]
df5.reset_index(drop=True, inplace=True)

dfn_1 = df1.dropna()
dfn_2 = df2.dropna()
dfn_3 = df3.dropna()
dfn_4 = df4.dropna()
dfn_5 = df5.dropna()

cds_rupiah = ColumnDataSource(dfn_1)
cds_baht = ColumnDataSource(dfn_2)
cds_rand = ColumnDataSource(dfn_3)
cds_euro = ColumnDataSource(dfn_4)
cds_yen = ColumnDataSource(dfn_5)

"""**Figure Rupiah**"""

# Create a figure to display Rupiah Data
fig_rupiah = figure(
    x_axis_type='datetime',
    x_axis_label='Date',
    y_axis_label='Rupiah',
    title='Rupiah Currency Value U.S Dollar Exchange Rate',
    toolbar_location='below',
    plot_height=600,
    plot_width=800
)

#  To display the rupiah line plot
z = fig_rupiah.line(
    x='Date',
    y='Rupiah',
    source=cds_rupiah,
    color='red',
    legend_label='Indonesian Rupiah'
)

# Bokeh Library
tooltips = [('Rupiah','@Rupiah')]

# Added HoverTool to create fig
fig_rupiah.add_tools(HoverTool(
    tooltips=tooltips,
    mode='vline'
))

# Rupiah Date Slider
rupiah_date_slider = DateRangeSlider(value=(min(df1['Date']), max(df1['Date'])),
                                    start=min(df1['Date']), end=max(df1['Date']))

rupiah_date_slider.js_link("value", fig_rupiah.x_range, "start", attr_selector=0)
rupiah_date_slider.js_link("value", fig_rupiah.x_range, "end", attr_selector=1)

"""**Figure Baht**"""

# Create a figure to display Baht Data
fig_baht = figure(
    x_axis_type='datetime',
    x_axis_label='Date',
    y_axis_label='Baht',
    title='Baht Currency Value U.S Dollar Exchange Rate',
    toolbar_location='below',
    plot_height=600,
    plot_width=800
)

#  To display the baht line plot
z = fig_baht.line(
    x='Date',
    y='Baht',
    source=cds_baht,
    color='blue',
    legend_label='Thailand Baht'
)

# Bokeh Library
tooltips = [('Baht','@Baht')]

# Added HoverTool to create fig
fig_baht.add_tools(HoverTool(
    tooltips=tooltips,
    mode='vline'
))

# Baht Date Slider
baht_date_slider = DateRangeSlider(value=(min(df2['Date']), max(df2['Date'])),
                                    start=min(df2['Date']), end=max(df2['Date']))

baht_date_slider.js_link("value", fig_baht.x_range, "start", attr_selector=0)
baht_date_slider.js_link("value", fig_baht.x_range, "end", attr_selector=1)

"""**Figure Rand**"""

# Create a figure to display Rand Data
fig_rand = figure(
    x_axis_type='datetime',
    x_axis_label='Date',
    y_axis_label='Rand',
    title='Rand Currency Value U.S Dollar Exchange Rate',
    toolbar_location='below',
    plot_height=600,
    plot_width=800
)

#  To display the rand line plot
z = fig_rand.line(
    x='Date',
    y='Rand',
    source=cds_rand,
    color='green',
    legend_label='South African Rand'
)

# Bokeh Library
tooltips = [('Rand','@Rand')]

# Added HoverTool to create fig
fig_rand.add_tools(HoverTool(
    tooltips=tooltips,
    mode='vline'
))

# Rand Date Slider
rand_date_slider = DateRangeSlider(value=(min(df3['Date']), max(df3['Date'])),
                                    start=min(df3['Date']), end=max(df3['Date']))

rand_date_slider.js_link("value", fig_rand.x_range, "start", attr_selector=0)
rand_date_slider.js_link("value", fig_rand.x_range, "end", attr_selector=1)

"""**Figure Euro**"""

# Create a figure to display Euro Data
fig_euro = figure(
    x_axis_type='datetime',
    x_axis_label='Date',
    y_axis_label='Euro',
    title='Euro Currency Value U.S Dollar Exchange Rate',
    toolbar_location='below',
    plot_height=600,
    plot_width=800
)

# To display the euro line plot
zip = fig_euro.line(
    x='Date',
    y='Euro',
    source=cds_euro,
    color='orange',
    legend_label='Euro'
)

# Bokeh Library
tooltips = [('Euro','@Euro')]

# Added HoverTool to create fig
fig_euro.add_tools(HoverTool(tooltips=tooltips, mode='vline'))

# Euro Date Slider
euro_date_slider = DateRangeSlider(value=(min(df4['Date']), max(df4['Date'])),
                                    start=min(df4['Date']), end=max(df4['Date']))

euro_date_slider.js_link("value", fig_euro.x_range, "start", attr_selector=0)
euro_date_slider.js_link("value", fig_euro.x_range, "end", attr_selector=1)

"""**Figure Yen**"""

# Create a figure to display Yen Data
fig_yen = figure(
    x_axis_type='datetime',
    x_axis_label='Date',
    y_axis_label='Yen',
    title='Yen Currency Value U.S Dollar Exchange Rate',
    toolbar_location='below',
    plot_height=600,
    plot_width=800
)

# To display the yen line plot
z = fig_yen.line(
    x='Date',
    y='Yen',
    source=cds_yen,
    color='purple',
    legend_label='Japanese Yen'
)

# Bokeh Library
tooltips = [('Yen','@Yen')]

# Added HoverTool to create fig
fig_yen.add_tools(HoverTool(
    tooltips=tooltips,
    mode='vline'
))

# Yen Date Slider
yen_date_slider = DateRangeSlider(value=(min(df5['Date']), max(df5['Date'])),
                                    start=min(df5['Date']), end=max(df5['Date']))

yen_date_slider.js_link("value", fig_yen.x_range, "start", attr_selector=0)
yen_date_slider.js_link("value", fig_yen.x_range, "end", attr_selector=1)

# Outputs to HTML Plots
output_file('Kelompok Afkar & Diva.html', title='Currency Exchange Rates of Five Countries Against the US Dollar')

rupiah_tools = column(rupiah_date_slider)
baht_tools = column(baht_date_slider)
rand_tools = column(rand_date_slider)
euro_tools = column(euro_date_slider)
yen_tools = column(yen_date_slider)

rupiah_layout = row([fig_rupiah, rupiah_tools])
baht_layout = row([fig_baht, baht_tools])
rand_layout = row([fig_rand, rand_tools])
euro_layout = row([fig_euro, euro_tools])
yen_layout = row([fig_yen, yen_tools])

# Create five panels namely Rupiah, Baht, Real, Euro, Yen
rupiah_tab = Panel(child=rupiah_layout, title='Rupiah')
baht_tab = Panel(child=baht_layout, title='Baht')
rand_tab = Panel(child=rand_layout, title='Rand')
euro_tab = Panel(child=euro_layout, title='Euro')
yen_tab = Panel(child=yen_layout, title='Yen')

tabs = Tabs(tabs=[rupiah_tab, baht_tab, rand_tab, euro_tab, yen_tab])

show(tabs)